apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- https://github.com/kubeflow/manifests/apps/pipeline/upstream/base/installs/multi-user?ref=v1.8.1
- https://github.com/kubeflow/manifests/apps/pipeline/upstream/base/metadata/base?ref=v1.8.1
- https://github.com/kubeflow/manifests/apps/pipeline/upstream/base/metadata/options/istio?ref=v1.8.1
- https://github.com/kubeflow/manifests/apps/pipeline/upstream/third-party/argo/installs/cluster?ref=v1.8.1
- https://github.com/kubeflow/manifests/apps/pipeline/upstream/third-party/mysql/base?ref=v1.8.1
- https://github.com/kubeflow/manifests/apps/pipeline/upstream/third-party/mysql/options/istio?ref=v1.8.1
- https://github.com/kubeflow/manifests/apps/pipeline/upstream/third-party/metacontroller/base?ref=v1.8.1


- mlpipeline-minio-artifact-secret.yaml
- certificate.yaml
- kubeflow-gateway.yaml

# generatorOptions:
#   # mlpipeline-minio-artifact needs to be referred by exact name
#   disableNameSuffixHash: true

# configMapGenerator:
# - name: pipeline-install-config
#   env: pipeline-install-config.env
#   behavior: merge
# - name: workflow-controller-configmap
#   behavior: replace
#   files:
#   - config
# - name: ml-pipeline-ui-configmap
#   behavior: replace
#   files:
#   - viewer-pod-template.json
# - name: kubeflow-pipelines-profile-controller-code
#   behavior: replace
#   files:
#   - sync.py

# secretGenerator:
# - name: mlpipeline-minio-artifact
#   env: object-store-secrets.env

patches:
- path: pipeline-install-config.yaml
- path: workflow-controller-configmap.yaml
- path: ml-pipeline-ui-configmap.yaml
- path: kubeflow-pipelines-profile-controller-code.yaml

patchesStrategicMerge:
## replaces config and secrets mapt generators
- ntnx-config-patch.yaml

# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines

# vars:
# - name: kfp-artifact-storage-endpoint
#   objref:
#     kind: ConfigMap
#     name: pipeline-install-config
#     apiVersion: v1
#   fieldref:
#     fieldpath: data.objStoreHost
# - name: kfp-artifact-storage-insecure
#   objref:
#     kind: ConfigMap
#     name: pipeline-install-config
#     apiVersion: v1
#   fieldref:
#     fieldpath: data.insecure

images:
  - name: gcr.io/ml-pipeline/api-server
    newName: quay.io/ajaynagar/kubeflow-ntnx/kfp-backend
    newTag: 2.0.3

  - name: gcr.io/ml-pipeline/frontend
    newName: quay.io/ajaynagar/kubeflow-ntnx/kfp-frontend
    newTag: 2.0.3

  - name: gcr.io/ml-pipeline/metadata-writer
    newName: quay.io/ajaynagar/kubeflow-ntnx/kfp-metadata-writer
    newTag: 2.0.3