apiVersion: v1
kind: Secret
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: mlpipeline-minio-artifact
type: Opaque
stringData:
  accesskey: ${objects_access_key}
  secretkey: ${objects_secret_key}