kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:5lVwxGtYXHLa6wvJWhRCvC87Ix5pGPTgRfE2TEIwz/FZJb/CWekK5QrGmNxtyivsN0w1Sua2XtU=,iv:Km9H6gUnO6QujWWpt//DXL1jFYdjsddJVdeH8Ga+M98=,tag:CBifZXesXafyOZOEjzFFlA==,type:str]
    github_user: ENC[AES256_GCM,data:UDNNJGUg5StRj9F6yQ==,iv:1g0g7CcsocjsVdzCQetnZRzNRI14rfhq+FzqoRLhV94=,tag:42uXfbkUoe+hV+fDyoH2Ew==,type:str]
    github_api_token: ENC[AES256_GCM,data:yvHo7hIatM5A0vynWQAO9toIda1/b3sUa5TpWHbfitXw2nV4AXUqcQ==,iv:UZq3dU/aJXkEVVvUMB0xDdf8vqvk9zY0DUZyD1p3bF0=,tag:+3rmc2V2sS8EyXn8yWObzw==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:wNUOiq6HVUFB,iv:dZUDy/iXkcJJ2iJbjL/7kOawDHQCqVnHnzna3e+OuJ0=,tag:eGGLX05nJtcb6Xss5MbBhQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:GEF1OAL/ExE1151Z5kuD/sZikg8=,iv:OB/et9M45fOawfLX003eX3JUFqN5k4wJQgKJg1RTN3k=,tag:BkmudPEHdk+1AiyruL3IRw==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:9SMvrc3rZE/Px8/xG6YPEWAOblnu5ObdYVLtN1eNCOQ=,iv:JP1lIpx46+KZAVIN6EzGfj+xfTxqCPNyHAY1P7ttB/U=,tag:xGQtz6DLVSEI/Wd7L8Zqsg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:jjbBmjs=,iv:KynUMOBmWGyXP/HQy9l2CY2RlbA1jOTxa0dJ8owyRZI=,tag:DZMhbayE6yQ+KqonMff/0A==,type:str]
    prism_central_password: ENC[AES256_GCM,data:LTyn/1CuiXxZi/4=,iv:AYlFjMgWoHT3LEwgJum+TOT/bZpz2kvkQURjhGvhWE8=,tag:0+Snpy7dwBaaerxrWWT4yg==,type:str]
    objects_host: ENC[AES256_GCM,data:MLvftdg7nXsYWdfgR7cTih7LvVpZzZtuGw87W5wM+ELcMWrgsA==,iv:SskYar+l0GbprdmUwNHalm1RMrLxgNixNmVP093Wx/s=,tag:ftgGZA30mBotf/q0gpOEng==,type:str]
    objects_port: ENC[AES256_GCM,data:TWY=,iv:gVGugalK4O9KNVSfIFSzX0XnW+f2J1vbdHvN6CnXOAs=,tag:XVdO/DbOpMCbAaIg0lCc+w==,type:str]
    objects_region: ENC[AES256_GCM,data:kWdDSB/sRd8d,iv:H2MifECtqHl8xtJm5GMYdIO36mOpQGsTwh1mFn7OBn0=,tag:SrgEvgE57DZlTWKXMd1cPA==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:pZ3Fxn0=,iv:LPkpqbddjE2PQQsIZbpgpcqyTr+YTex8fuj25rHD3MY=,tag:t/uwm76z67Uq6nQjfkbiPw==,type:str]
    objects_access_key: ENC[AES256_GCM,data:fQZTneiy3AiZao4Fep3VyWdGN3zq7m+yUG8d0edNATw=,iv:bf4oe5gBnWy9jFKP/jPsb0mt3CXQ/y74qRDebVBGHAY=,tag:yrSxTnWtn+N0y6DqTlbHfA==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:30l54r2Cznpcriop0CuURT9gdcCp2a+IckVHKUUp0Kc=,iv:QJqXynIfXXjywc5Su++S9KsD4vbdplqBodPiWGPJ3mc=,tag:ouVlBSaZj+xfjmStC25nrw==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:F4D42jCltcCTRrkhDj6yLgtrXibxgJ0M0w==,iv:Ww0O4ZlvgWV9KOl7l9tMBlktB77Gi3WETvIoX5Vq+Lk=,tag:eNNFeY7ZGpclMle7gk6ksg==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:DZnpQHGmjL72j93jitHH,iv:MluEn+XO0EmIG2CndyhZunLO+on/XXPNrGZogEnSDdg=,tag:ccyV9XLysOH9uPEeilWOdg==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:tavrjZu3gItMMmsDthj2OpcQIUxAQHV7XxqAKDgO/Q==,iv:VsJPJzqirN4WVJDrasehg09BXF0xjaxfIPqKI/FX980=,tag:IwpUnL0C0H2dbFodcMKzVA==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:cr2vYx59vbH5Hl2EO+dFjrMbYBsrg8rqXXTKd5084n0=,iv:u41Ocy9vnAqNS2IQV9I7u2mjjr/tTBLDh9Y/3H281rE=,tag:FHHn77kSpo/3liVonBTdXQ==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:t/SRPxtmbX9A+1U81hR4,iv:UfQ64Fid3QoIZKvp5NNoMW3bsiWtnVz/J5qAM54Uu7E=,tag:1yhPM3NbEjIn8UEAoGW01Q==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:oddkqER+1VrJN4If78PezxJ5GMvwbCh6CXVH++iJDw==,iv:tui9AwhuNES7X9QxEOUOA0sRKNqba+y7aguJ37mT1us=,tag:HduPgViy4l7Cn4rCpKiujw==,type:str]
    nfs_export: ENC[AES256_GCM,data:x/Z3HW7QiXbYVukfHomwUg==,iv:WBRmD4wTRVKs6B/XJa4WoTxaxwNUW0C9Pe7ZNmEerFc=,tag:eKPA8mMfwyXfaQtGSZvU8w==,type:str]
    nfs_server: ENC[AES256_GCM,data:wI4HoFAMk8o7WFR1G9aMMPyyeWDtktkOfd1pQUEwXU86/Js=,iv:UR4p02ALwDMSCK6TQ/B2P4P0BCE/sVggV/EVkA8Xw2g=,tag:ks++ImTOTExxFYaP20misg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19swa2s5gqhmdr8uvh8jwcyxhg29p0shtandmqrtnlg48jc6yketqryyvfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMDl3NDNOVnA4UDJwcmwr
            V1BaWUZTLzc1aVdIUW9UUzdhbmZTNVdoMGpZCkZpVnQxdkphNDNESXRtenNid1lK
            bjFQQzRmSGlwM0ZGdlpnWHkwcmdjbW8KLS0tIGNxUmZvN1Q0UDBBYlh1bGJuanNX
            UG9KMXNBRmZuWDAyNEIzMGZsRGRlMVEKaqQZqkoXoEdbiq5vOyfSLWXX7EAPmszw
            bBEguC0RYcw3RdYBvpzcp7MZJ3QqMJeIn4HTfMc2WUnE2rJFu7n5Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T08:03:09Z"
    mac: ENC[AES256_GCM,data:7nI4EuUOdDLotQWQPsav6TI55XuwYGeO+fv8CLP00O4sPxARWWcHRwBqu5ZSKm+/PcGyogGABoKWabliXeFlenuIjvzwund7Y909DFQSQ0eoDJ2xVyZ98BthbUo5r5r+Za8aHiaFBEyttSGrLx1uy4hd4WVXInKetRSqAdIufUs=,iv:X6X1IUzO7Y5DpASp0Kxgz0YrWYenEiyXMF8iBv5SO8A=,tag:qUFIGzerCWszWrfhPQFgQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
