kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:u6lO8NAZJueKjlFdS3rxCBZUabOd+cIxe3m3gATYpWmP3PqLJAEtkrAwcOrSaPXUdlqY7JOYb70=,iv:vRfjm7OIvfd0IlKdz7gluj1ad1FFvcrjHm6l1L60sPE=,tag:lRoQ35LaMwnNIxqXCr2YLw==,type:str]
    github_user: ENC[AES256_GCM,data:l9SwjLw/2DPgZ53P1g==,iv:UcntvDEoyDOZeaX8pjxu46jPCEGDbJDZOzoaMNHOAtI=,tag:Mwwqz5QE5lawIOmTfyeykw==,type:str]
    github_api_token: ENC[AES256_GCM,data:xV9dMZQNL/Qu+egK5PwKNiHRzMSY2fLLMFm8aCTJJmhslpa6XBl8tA==,iv:Onkq1Xq2zJEF3B07S2WXq2P8+HHsQwAG+7IKIbCTpU4=,tag:pUS8ZUFxAUuqbBCtaatm3w==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:cvp/5SXPilbo,iv:dex0/fNRWOPZqHGdxvqrT4k0u91R4fW08JKszHtlpWI=,tag:t5aZoKI4+NoK0pcfNyjlWQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:/Rt/UMg6FzjO7iCnY26IvG4bQkI=,iv:/Q8o2+Kg7bayF8kUIA/NWvE8NSnw9s91QetIEKKJRHA=,tag:cPAXPdw++HvobjvMA6Dm4g==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:MLQK8cURA1DujGab6MGzijIyMUMShELxOkoDO10qVL1JLO+OZQ==,iv:qk/aY+NQaA0xMk0sATQF7tX5e9qeFZvpNyAFUwpdwNg=,tag:gqAERY0ZOEXkGBdUQ/RbEQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:tWrOgN0=,iv:+yIluv5P41GHC0bvdYBGrVRP2tXQgeRXzMZc3/G5u04=,tag:HLZ7n61ISj/8JKcvtv0GfA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:gY//OcQZR6QvQFI=,iv:P4T8dq2XxqFD/2/BVpffHYEeo+oqE3gCalWf975aYcw=,tag:0AqV/RC6ZuiDDHBx7shzfw==,type:str]
    objects_host: ENC[AES256_GCM,data:255bo6JCszLn3o0ro9M1Qf/jtkEUT1oKfg6kedS2a4YNMogLg1A3Oio8,iv:0M1/WRokrBOoR20Pjxn+3qVAG1I+3aHTB8e0sM4Dbeo=,tag:SOsEnmcQWe6Vt4GnO4pbYw==,type:str]
    objects_port: ENC[AES256_GCM,data:vxs=,iv:F2vP88WKKx5Ikl57R7jGSXgqzSqg4SYt2RskhH/wIKM=,tag:HRppyptqDdP8kMsvWGwzcQ==,type:str]
    objects_region: ENC[AES256_GCM,data:i7C76KxXq2E2,iv:E3Isf+U5h6EJzOvAnOd85gr4dzjxuw7k0No76Jrk5CU=,tag:rHCgEcCWxSG+OajpCgbGfA==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:EaIBZBY=,iv:lLOdpIa4i5Z592aQuaEEmBdgguNyTduNBn8kD8C522c=,tag:QAdHwyeyw3P3dm0VASmATw==,type:str]
    objects_access_key: ENC[AES256_GCM,data:zpKCyS8nfinyBuNm3b7yE3qdEgXeeznsIhnNz2RhPFM=,iv:+N1VDZpu9DPwWUXsOf0vAeZvxMf+6hD1ZEZAyJNhiq8=,tag:rWtyk1d6G3UV/a+rgI5RqQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:pRoRaOky9bV7pO3Lvk2B3QAnrEjmV1UIN69jr2kAecQ=,iv:WXxce3a5WtbSVfkZiXL+Rs7Cme+CvlryYFzHWXNfBA8=,tag:lWC3BKtKMkh/c7WTdj5vCA==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:dVXW7mMF2X0NhytLGiKR5GMuOPzKPZdTdQ==,iv:+pNvdy5QD4IZBo0d7JpCRspU6L/2b0kR/GC1+PFAhUw=,tag:+a531jnBLTn8ZYIK8l4CMg==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:XTegC8swr0Zm6SYqpOQj,iv:b9p3BCDGU5zrSx/oOBXthkh+cD8VhsFGch+Hr6Qo1so=,tag:SEfgQEwLnyYxWhYxCM2/jA==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:HZ+evfE9SWwKMY3GD/GZdMBsoHQymbB6eFJucvTDkQ==,iv:JBEePXWmbZJAsfg7VedUaMTfzRawKeck0eaxdH+l30Q=,tag:JRt7f4nr/HUBOcbtq5VFRw==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:0JMpDugBVkU6/qBstoFpa2p2dr/aVrSdjjDJs+Ey2Z4=,iv:VEwK/1iIjDXbboFN380ZH/P8EZzyKg99lzzBeRye90c=,tag:Dc4+5Ekbn+idvhoprlXzfA==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:fZ3Dc4rIH3Tk/jd5olRy,iv:/bnoFvvxRcNTtUrMPcypKbJ+htD5xuaUJ7CuOaJVKa8=,tag:4q06TYjzz3gpptww3hmWdg==,type:str]
    istio_vip: ENC[AES256_GCM,data:owLD07OYTMvC2iHs,iv:CUZ5NjUDT7bzKifFvmlVgM6lCgylqmQMraXywpI7PcY=,tag:0Gj4Ycav8gadYKW5Jks42g==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:RzNkC7zXq+nrigIk+yvgbG2CmsrkUBa4ZgKzamMWVQ==,iv:gQ2ugdT+LlGLseKjXVptkvW/gxkWzze5RsZjNlqSZPM=,tag:sQ9vLqYF/Qgq00/dnTVFIQ==,type:str]
    weave_gitops_default_pass: ENC[AES256_GCM,data:ypkYZ+6S8qImMJB/CdtVGD4kr2mRp27DFiwkvS2zQMz0D+AB+8NvFHZA812UEoRa4IOGeijGUtlezth5,iv:3icX/VSkMGY3b9y/IuDA1cRYpas8nJPrWjOLQcwgFCQ=,tag:hEJ5vpIZYD4qc/HAojnLiA==,type:str]
    nfs_export: ENC[AES256_GCM,data:ZwcB9gzLjHZhtpBn7MFzmQ==,iv:df1UmjzNQpnZc0jGDl2WAyHM2d9BRhntBNw0Jaoo7Bo=,tag:JeZhdJalR755aaxZ5OQnCA==,type:str]
    nfs_server: ENC[AES256_GCM,data:NNLBThvqXYtQgJCrk38CC97BCNNErtsz+L2juSZPpGtXSpM/PI/Hlw==,iv:lWXXtddhX0OoIoHRXL5GQNSJ5ZZ2AwgVb2DSeQ7DFjE=,tag:IQ3mGvjklS+5qTAJ2FRA6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age104c0tkxyvcd7kap4p6yfkactkvz2evrlnrx83f2mjtguv3d0fc7sczadr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdzVwbXJHaDRzUXIvbm1P
            dVk2NVF3SHBjNlljRG54NGlqbXA1RXF0bXc0CktzY2JRMzFZSzU0YXp3MktQVnJC
            VnNWcTFhSmk3N0pNdDhDOThLaHowb3cKLS0tIDVzNlBtSTAyUWxzNVBseHRDVUwy
            c0w2Rmo4MG5ETEdDVlBsZ29ndnNhRG8Ko0Z5CsceIM1qAu+wyOanjeBTJoa28aHG
            DOXverzQNs6tTa2dY9qF0xfCNTUhN7T6yw4sOL3cKe4xSwJgHI70Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-02T03:24:28Z"
    mac: ENC[AES256_GCM,data:wPsfmq3DScEk3Wnf3i3WWO49wBnS9YUCvqLSey9NSaYNhrxTVgrqu4tZpMLx8eDF/XZ1EMytzcF/3/6mTSdAI5nitwy8GdsAqjgCnGCCS7oNxJLGGrKGJpXjwHBxCorW+MRHZNYlyH/3f9ntO07R0GuCukG1oClmp+29edKinfw=,iv:mExo07M+JFX9KpEpFBlC4g9w7y+ckRnB+kqWbmo9HlQ=,tag:rQXEmjYmFateAYWVnmt1KA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.9.0
