apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- ../../_base/kube-vip-repo.yaml
- ../../_base/cert-manager-repo.yaml
- kubeflow-repo.yaml

# patches:
# - path: kubeflow-addons.yaml
