apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../ntnx
  - https://github.com/kubeflow/manifests/common/cert-manager/cert-manager/base?ref=v1.8.1

namespace: kubeflow

# Delete the cache deployer as we use the cert-manager instead
#patches:

# Pass proper arguments to cache-server to use cert-manager certificate
patches:
- path: delete-cache-deployer.yaml
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--tls_cert_filename=tls.crt"
  target:
    kind: Deployment
    name: cache-server
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--tls_key_filename=tls.key"
  target:
    kind: Deployment
    name: cache-server
