kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:asmNtq9IYHrfBgRURRg7ZsdC7lx+GAMTaduzstpCygDYueL8VmGnS7YlbHgbTp0Yf+cVrkKkCVGO,iv:PWCYBbaDUxdetAV+u+Mk68IbSdDKAHXKeuaqQ7Q00Uc=,tag:6TZJ+XOoWBGoVBqgMVFw1Q==,type:str]
    github_user: ENC[AES256_GCM,data:LsTNgw6ns14lB4NynZ0=,iv:QHuP9d+CiYNhvFNS8TLwF85R8BuMNKpoH8kGVz54axA=,tag:Hw49YgfD6dPJbHiCNCgkOg==,type:str]
    github_api_token: ENC[AES256_GCM,data:btMjTDP7tdjtvxTScILzbX0Jlx8W/XJstfiuhAKSvN5tXrR5gdcOWA==,iv:OE9ouxyFMMcP+TTAH1AaIdai2/eRztlgqraD2JuZBgA=,tag:BfqZlat1fGsIjoi/IRu8Pw==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:cs6diPAbPnH1UgOU,iv:u1h/LD+Q8OU9FVAEfJB1zWVvxkqtJrmrrM6njsqI0vU=,tag:9PE7DkaRLEdeEq7NtJkgFw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:+HG0hPZ5jzGkZYq96NXH,iv:IgDfTRMmY1LjQDEmwOSGtyvbmThcMaG1mR4v6pk072U=,tag:qIpfEiEA4V2aTK4ynCRUzg==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:11H1OV0dhth2r+Fu+9WVkQisMfz0U0FolQNlmR9gWdqQvi2sLQ==,iv:1fw4HP81ELllYaqJP19Wjl0r2z/8DjVK3uf5wojlh2Y=,tag:TYqFVyTHCPwXjZsuaqf9ZA==,type:str]
    prism_central_user: ENC[AES256_GCM,data:r/+R17Y=,iv:xG9VotvN1+euyT754OleKkSmL76vnALJI9FV4iDBffA=,tag:mIlBZaMdD8U8EbtxhR3Zqw==,type:str]
    prism_central_password: ENC[AES256_GCM,data:tVRyv9jYCItJMVA=,iv:HVLP2L29J82vknui7W6zjp9OOex0dh75DZziP5rc8/I=,tag:0qdmp1fPXcHokfkAyvoz9Q==,type:str]
    objects_host: ENC[AES256_GCM,data:mK2XpvORiRG3V1+fldvE1zFvwAM7ay2vJzN7DcsLj0YcBKnwsltz5NWN,iv:h8Sfgq6f+ot0cGrOkXLrphDRhXC/jL/7U4CekVfyEyI=,tag:Nw9JTME4LeQQHZUr1Wf/FQ==,type:str]
    objects_port: ENC[AES256_GCM,data:IqI=,iv:6Dhq+XXKDwyWdVsLaYpB7sQRfeemSZ/Zo6a6OQVc1WE=,tag:r9b1NWKVH5rCrbG71eQeXg==,type:str]
    objects_region: ENC[AES256_GCM,data:grEgAyYYGmdY,iv:tTG0natWcGG1U8k9lK0s3UHLONjPLVPo7J4yXDsAnCs=,tag:mpwSOv3OZYGq2gj9feqrqQ==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:vjqvTwU=,iv:GanjqUgU/OCAtCyulASXuLlXip+Qes9dPBHFeoh830s=,tag:cQ1P/PeDpK5la1bRFmoASg==,type:str]
    objects_access_key: ENC[AES256_GCM,data:1haz4eylIT1SXFNR+dz+v/ffVDjiKJq1VibjS9i51nA=,iv:DObquOwoSFlYRDXwhInY0qzB3XsGp++PuaergFPOD/M=,tag:62Ddm7cgG9CStaFaDi4CDA==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:tY/UFVqStoWoixGUnUoI3UhzEE71kEHDtx5XBovU4Lw=,iv:mnN1xLFbo3f+TAFiySpOvIHvWmhk9wN+zK8CN2DyhPg=,tag:emwOuXZI1/fLM2BCmuGmuA==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:EVeyHKZeegwnZn4YhYV2dy08WZIdE48=,iv:gNFlzHdGFOA+mG5u9uR/RonXHHTpEPdUzZmHsb9SOSM=,tag:Jp9ilJEOE2pbnIe9xYd4JA==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:EB+UeKH4K88YFkz0Ck8=,iv:v9G5Q2J0YGpZXMt0aBafTMEcvakYg3nLO402erGCrwQ=,tag:ZcOswTEzUWs7W+DWZeOAFg==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:rbTbheiiduei2uZNCus28DwhNm0UmKftjPyC+9R0LBl+jGc=,iv:ZAOINsQ0DYXfacUOiYy0t9E4lTS9thLvU3hQ2r3J8rU=,tag:8EZjdeX5FJsyBKH+WTe3Mg==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:DWnRDzY8BHF69z+6txr26geoTi5VIp1uN45yOu04DH3VZS8=,iv:BRxGpo2ycvKYdf6oPAwcQRg4Xo9pnqUW3/w7cRRXyHY=,tag:ZirJe0rz2KchebkARDymxg==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:BvTesnDDrAvF89BPzpU=,iv:hRN2Xcudugybv0UoOy35/cmwmAoKW3KZedEhKPwhAh8=,tag:r+ts8lgl4btH/eSJO0/7Gg==,type:str]
    istio_vip: ENC[AES256_GCM,data:iXfhepBXzN0nUek=,iv:+TBgsKcM86Jj+LBUWZdLRb9RlSPHUiMdViXxxtCMbBc=,tag:7YkKVyNn7TvH5+Ib15R6TA==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:6YXROtb4Hf743wB+ST6OW93kl7dfQF+IEpn3eJIynTwlreA=,iv:/JrqsYsD4cTQDGqubLSOZEP6l7Nex3xbPmXo66zq8ro=,tag:jDuRvX7bGFiBhGbDUyP1xA==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:A5D0I1sHGhr4CrxkHPj+LhB5Zf6vDD/A2Q==,iv:Tae1pDZVCI5nxftzyRCMQqlzwOwlPtV1CiiBdDnQLaU=,tag:wZvFggl3VzpPiS1NkHS/Kg==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:Ydc/qhj2YW/jc6LrMxG6S/HazYwuiQ==,iv:t1z5rOugmjM3aTRoTYwlporwXGbL+v+wgbWqrn2Bw1w=,tag:nj5Hz6pwqLbK7vMUGA9rNA==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:qKT6cm+uAHmG,iv:plxh5AeONsnE7tWjmiDqUnWayckHuBPKHHAECt9KNe4=,tag:whaYuzx4MCMIv93flL4Mtg==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:vYOqteJIWz+YzvRj5dDx4QZhX6Z3,iv:2iRG4xjWU2F9Ioo1W86gGT1SRhDDqdn9o+t/GhQ7DmY=,tag:PAGOGwpHK0RXhMuOYXuC/w==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:P4ykeh3RvLHnzuUuS3kNrLA1eKw=,iv:M4f2lCC0SRcs52PDdPoy8V+gbCfuDm6k4dhQek+FwBw=,tag:15A3E44RlLHi9z2nmnoKuQ==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:gF9+HifNVkoN+UHjRZ8WOV+jk+G8Yjeq/yElX8hR8amSRf+zU7Ejbw==,iv:lMcM6gaE8+CXRSdFI2EeaRtCGU3//0VnkUhZJO5i720=,tag:JB38ILblzknsvUZXJCmiQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbVZ4WDlsN2RJY21wM04v
            QUVNSDZiU1g5YnZGcThVbFk4d2R3Y0ZqalJNCnlDOFhUV1lXc2d4WXRQM0laZjhQ
            anlBa2dtTGZQaUh3ZTdpMmdtazdNd0UKLS0tIDhaSFhnTGpmNGlFaGFFK3pUcytY
            QlhYRFpvM3VJaFpIYmg2cGNicE85dDAKiIgfQmojwIZlRO7RAG1XJka3gsLnYgAA
            FMAUTrUYXeQKEgNa9UZhxC/aY886hZxFJIg1TzWo7wvG7zAhjK36Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-11T08:52:34Z"
    mac: ENC[AES256_GCM,data:dpTLF35mntzcrNhBqzfNrMvMyxH6K13mQyzJYZqLDXNHTjt6z7eyEUO0ShfbdkMCOWvs5E4eFv4Ss9P9Wn0yMK4sIsbqbHSWhw3iFWjPg0sUXGX7+1A1kBYeRZYwRy5gtyDIZpAhZGuMxtreyAXaZPd8xWiApVf+KrfTpU69gWE=,iv:/pgRkn54vAdiA7RZV2asUAqzGhaH9cq6mIytF7H4x1s=,tag:6CFKr2It8NSaODtqjqawbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
