kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:nyLtGRFCuubnjEfDWyqQFKsbu4UZ3g3e+21tKBBZ+ioSugjanNfJZGuj5CtCrtBvE4BmdCILXrY=,iv:nmSDAMGX5SwwWDvDV1c/7tdTpv7zEQWL8IhynRKl9Y4=,tag:ttaYQupa/P3wjcD0M5wI0A==,type:str]
    github_user: ENC[AES256_GCM,data:NX4MFkJ0e+EiyvnpiA==,iv:tQ2puDUiZGHrHO8WpLNLGztbroC+/JmEl465ECKtvGg=,tag:dwlx3egtgSaLuhErGxvGpQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:QvJJDQF/fvDl969JeqwCO84oGYBGI/l4bfN83FIbWxI7Obd1XNmriw==,iv:lKgXoBaQ2JVpwR1GBc4orsbcLQTSGDy6Sf07VqfzQ6o=,tag:u4yB0sdnObKssDOJxPfNqg==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:ztGrndB5qSLv,iv:3udE81QKehu4PgqygKVuWjSHi0BC3yr/AjhERj5NZfg=,tag:tC/eOsKFMkDBIrwRFHn+Mw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:aDUMLQ9CNO9X72Rt0/anLdzqtU4=,iv:EUpHDd5kInfoq3z8TZsSNFhQ+GKmNnr1EOXAzhoz1e4=,tag:iZGLCN7cZROUJep3PMK0Ag==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:R7Yt6bore+KBv0w1gWmFpx1+jICOKNMqjJQArFkMQ+A=,iv:2u+ZZ15HtQQDpPuCcMd84WEn7VBC9s4vNBtCWJyTeOQ=,tag:c0NHhG26GgGgyGzMC8BUXg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:mkFetmc=,iv:antvMRew5zsP6p0SmqObSGZtEjV4GBhWjnIAcyObiTw=,tag:kb2yNHXMGaFDDZaU0FX+SA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:wMwA9YuxLP/19Jc=,iv:INHyBZK90Twq8U9lcoDa8RSnJPebs9JkrL0lTA5pprk=,tag:k2DJEhEbQ9QXK124xYSQBQ==,type:str]
    objects_host: ENC[AES256_GCM,data:9/vJShMdrv9Ip2F8SGRfVhEQOB6bxEpY8CmEo55a2TO59kVHdQ==,iv:L3wwizsGuXx9UZZz2tHlIk3P5W7rJdplPq+RDPyrnvU=,tag:Xta9yiyLkDRExyrVNOHcMg==,type:str]
    objects_port: ENC[AES256_GCM,data:ErE=,iv:uCZRk6/8WfbZVBMGQU8kkYFU1LCZK/zKEo6r3Tdynqs=,tag:qj44otNWU+XC3cIhApqjZg==,type:str]
    objects_region: ENC[AES256_GCM,data:VGA6e4YTZYKL,iv:TPvZHHTYtL5C+nKv9iBGTrlFtnGhgcPMVBKMgFoAX1Q=,tag:TlWOquWSJvFi0SVb7Cdkhw==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:bLlFxYM=,iv:dmO408VLuZA5RhCT9sOpeS5tB0iP/0tG5+C9+rhc/sc=,tag:xDMBEtIhCQcRPMgL0qtuMg==,type:str]
    objects_access_key: ENC[AES256_GCM,data:kgFL8Xy+wekHLzUSaeTkXJfB8FkZ5mk0A/JvmPHBTmU=,iv:BZbwGss8Rfl5JSRbYUDemfmRmWzhx2xoIEBJtVdp240=,tag:nyBdwoBP0XqT8UgQ7REjSQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:/nnFK2b9OKtEIdi2vQkUhw0ya01hZPR2ECi1aWgmfqI=,iv:NMLmej7H1B6Fxw/UJn8fMV1DPq+70nhnrYC4dijA1MQ=,tag:NfUnidoozv6OKJth+n3JOw==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:KRoKO8mYQR+FJRdNtgbJHs4gACOfIbsOkg==,iv:vDwe4snxw0FptDUxPR3iosoo9oX8tyvvFsl2FNOcogQ=,tag:CH8d1w1qBpTYFEOh5BovGQ==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:e0BUAf2nB+leEEqaVdlz,iv:qJqkDuo/7j3J7lARL7ph5lVy36wMlGlzaKEj/pDFH58=,tag:2hQ3fXbfMVbmByDPeNHJeA==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:TMv/ghBJfZwvW8yyAeQpgiOv7AigoiOrOinrbazZ62w=,iv:O6FbyWUjohQ8r100mbj+A9QsFLe8D9Qcrim5pP1zJno=,tag:iIuXypE8R3Og62XjJIa6vw==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:LEhYNAaZeFzIJhYXHlmijrpMV920/hEXLE6TJEeqsJU=,iv:Yx4hV9sgU2Jc0dMxksh5FcCi2McGLtd5Y2lbbGf6Kys=,tag:tatYrjetkK2B4HsyO58CFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19swa2s5gqhmdr8uvh8jwcyxhg29p0shtandmqrtnlg48jc6yketqryyvfm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZUtOTERXWm9KSDN0QnNi
            cWhCZjY3Y01oN05rdEJtc0dqWm1WaVh4MEMwCjdLeGszU0hBT1ZRNTJzWG5iQlQr
            aWdtWWFDYkZvaW8wekl2MVh0alZRSWMKLS0tIHJlWXpqTkxXcGJvTmNmeWdyaEF3
            aXBxdkxmOFRDd0Y5eDNBQ2pST3hWOE0KlJoniiF3cmGpxHQ5LJU8Shwql/bVvb4X
            wDIZ/6i9LHSa2JPMw0lVCa3deQEBFL8qHjHqwbqdI0y1rs9V9oxP8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-09T01:58:38Z"
    mac: ENC[AES256_GCM,data:Z83CvPyXpFPw5y3OZugbhd7C+zG9gMDkuHUlsXLIHwPP/t/aoelyoE9wUOO5kzHtsnhSotg1N0wihnPr0a0DnzBv4d7KbZkLZFcZRlIIU/5UgiapRv0FEna1cGFPZkD6H8ze16gESonJBoQsVgOAVYgktCLWOhFnLDPfrzcuuZw=,iv:lq0SncflrLnGcWfJ8Eo8x62+bD1j91hROR+ubdA228s=,tag:IVGyn+S5vIXuYIpWr7yUgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
