name: linters

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install yq
        uses: fluxcd/pkg/actions/yq@main

      - name: Install kustomize
        uses: fluxcd/pkg/actions/kustomize@main

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: ".devcontainer/Dockerfile"

      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './scripts/**/**/*.sh'